### ISSUE TITLE
Folder spacing issue again

### ISSUE THREAD

**Issue by MrBlazzar** [Juicysteak117/MinimalImprovement#6]
Hey it's me again sorry about bothering you but I did another update today and this issue reappeared:
![image](https://user-images.githubusercontent.com/5840012/97779848-42b20600-1b57-11eb-9ff3-4a33c138fec3.png)

Whenever I have a folder open large amounts of space are added to the bottom and it's size depends on how many servers I have in the folder itself
![image](https://user-images.githubusercontent.com/5840012/97779864-5b222080-1b57-11eb-9cfb-4d0005edd1aa.png)

Again sorry for bothering you I just don't know how to fix it myself and figured I'd put a issue in incase you didn't know and wanted to fix it.

Thanks for the theme.

**Comment by Juicysteak117** [comment]
I'll take care of it. TBH I've been really behind on fixing changes so I'll see if I can get it by the end of the day here.

EDIT: That actually took less time than expected. It should be all fixed now but let me know if it isn't.

**Comment by MrBlazzar** [comment]
Interestingly enough it did fix it for most of my folders but for some reason two of my folders still have the issue?
One folder not having the issue:
![image](https://user-images.githubusercontent.com/5840012/97787373-12369000-1b88-11eb-9858-ba4afde3a88d.png)

Other folder having it:
![image](https://user-images.githubusercontent.com/5840012/97787378-1cf12500-1b88-11eb-859b-2a9e5adfbd60.png)

The only two folders still suffering are ones with a whole LOT of servers in it. Not 100% sure why they are suffering from it but not any of the others?

Either way I don't open them to often as they are servers I'm not heavily active one and just check from time to time so thank you for the quick fix.

**Comment by Juicysteak117** [comment]
Ahhhh yeah I have to manually set the height at each level. The max I wrote it out to was 15 servers since I figured nobody would have more than that hahah. I'll add a few more though.

**Comment by MrBlazzar** [comment]
Ahh that makes sense then. Thanks for the fix.
